name: isdata_env
channels:
  - conda-forge
  - defaults
dependencies:
  #core packages
  - python=3.12
  - pip
  - sqlite
  
  #core Web Framework
  - django
  
  #Django Packages
  - pip:
    - django-haystack
    - django-simple-history
    - Whoosh
