# Generated by Django 6.0.5 on 2026-05-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='catalog.family')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ISElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('iso', models.CharField(blank=True, max_length=100)),
                ('length', models.IntegerField()),
                ('ir_min', models.IntegerField()),
                ('ir_max', models.IntegerField(blank=True, null=True)),
                ('dr', models.IntegerField()),
                ('url', models.URLField()),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='catalog.accession')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='catalog.family')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='catalog.group')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='catalog.origin')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ORF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_length', models.IntegerField(db_index=True)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('is_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orfs', to='catalog.iselement')),
            ],
            options={
                'ordering': ['aa_length'],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('is_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='catalog.iselement')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'is_element')},
            },
        ),
    ]
