# Generated by Django 6.0.5 on 2026-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iselement',
            name='dr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iselement',
            name='ir_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iselement',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iselement',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orf',
            name='aa_length',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='orf',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orf',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
