# Generated by Django 6.0.5 on 2026-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_iselement_dr_alter_iselement_ir_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iselement',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
